version: "3.8"

services:
    app:
        build:
            context: ./
            dockerfile: dev.Dockerfile
        image: bank-alpine
        container_name: bank-panel
        restart: unless-stopped
        working_dir: /var/www/html
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - ./:/var/www/html
        networks:
            - bank-ag

networks:
    bank-ag:

